name: Schema change request
description: Create a change request on the existing HuBMAP dataset metadata schema which can involve proposing modifications, additions, or deletions to the structure or content of the schema.
assignees:
  - johardi
labels:
  - Minor change
body:
  - type: dropdown
    id: target-schema
    attributes:
      label: Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.
      multiple: true
      options:
        - 10X Multiome
        - 2D Imaging Mass Cytometry
        - ATACseq
        - Auto-fluorescence
        - Cell DIVE
        - CODEX
        - Confocal
        - CosMx
        - CyCIF
        - DBiT
        - DESI
        - Enhanced Stimulated Raman Spectroscopy (SRS)
        - GeoMx (nCounter)
        - GeoMx (NGS)
        - HiFi-Slide
        - Histology
        - LC-MS
        - Light Sheet
        - MALDI
        - MERFISH
        - MIBI
        - Molecular Cartography
        - MUSIC
        - nanoSPLITS
        - PhenoCycler
        - RNAseq
        - RNAseq (with probes)
        - Sample Block
        - Sample Section
        - Sample Suspension
        - Second Harmonic Generation (SHG)
        - SIMS
        - SNARE-seq2
        - Thick section Multiphoton MxIF
        - Visium (no probes)
        - Visium (with probes)
        - Xenium
        - Other
    validations:
      required: true
  - type: input
    id: other-schema
    attributes:
      label: If 'Other' is selected, please enter the schema name below.
  - type: textarea
    id: request-description
    attributes:
      label: Describe the change request (use a numbered list if many).
      placeholder: e.g., Add "Aperio AT2" in the acquisition instrument model.
    validations:
      required: true
  - type: markdown
    attributes:
      value: For significant changes, change the label to 'Major change'.
