name: Schema change request
description: Create a change request on the existing HuBMAP dataset metadata schema which can involve proposing modifications, additions, or deletions to the structure or content of the schema.
assignees:
  - johardi
labels:
  - Minor change
body:
  - type: dropdown
    id: target-schema
    attributes:
      label: Select the target metadata schema name, or choose 'Other' if not listed.
      multiple: true
      options:
        - Cell DIVE
        - CODEX
        - Light Sheet
        - MIBI
        - snATACseq
        - snRNAseq
        - Visium
        - RNAseq (Visium)
        - Visium (no probes)
        - Visium (with probes)
        - LC-MS
        - HiFi-Slide
        - Imaging Mass Spectrometry
        - Histology
        - PhenoCycler
        - CyCIF
        - MALDI
        - SIMS
        - NanoDESI
        - DESI
        - Auto-fluorescence
        - Confocal
        - Thick section Multiphoton MxIF
        - Second Harmonic Generation (SHG)
        - Enhanced Stimulated Raman Spectroscopy (SRS)
        - ATACseq (bulk)
        - RNAseq (bulk)
        - RNAseq (GeoMx)
        - 10X Multiome
        - GeoMx
        - GeoMx (NGS)
        - GeoMx (nCounter)
        - Molecular Cartography
        - CosMx
        - Xenium
        - MERFISH
        - DBiT
        - nanoPOTS
        - scATACseq
        - scRNAseq
        - ATACseq
        - RNAseq
        - RNAseq (with probes)
        - nanoSPLITS
        - SNARE-seq2
        - 2D Imaging Mass Cytometry
        - Other
    validations:
      required: true
  - type: input
    id: other-schema
    attributes:
      label: If 'Other' is selected, please enter the schema name below.
  - type: textarea
    id: request-description
    attributes:
      label: Describe the change request (use a numbered list if many).
      placeholder: e.g., Add "Aperio AT2" in the acquisition instrument model.
    validations:
      required: true
  - type: markdown
    attributes:
      value: For significant changes, change the label to 'Major change'.
